I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,",","""",A,m,e,a,l,c,o, ,d,e, ,B,o,n,f,i,l,"""",",",1,2,8,",",1,4,8,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,2,",","""",P,i,n,a,l, ,d,e, ,A,m,o,l,e,s,"""",",",7,2,",",1,0,0,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,3,",","""",A,r,r,o,y,o, ,S,e,c,o,"""",",",2,3,",",3,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,4,",","""",C,a,d,e,r,e,y,t,a, ,d,e, ,M,o,n,t,e,s,"""",",",1,0,0,",",1,0,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,5,",","""",C,o,l,Ã,³,n,"""",",",1,1,0,",",1,0,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,6,",","""",C,o,r,r,e,g,i,d,o,r,a,"""",",",1,5,5,",",1,7,0,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,7,",","""",E,z,e,q,u,i,e,l, ,M,o,n,t,e,s,"""",",",6,1,",",1,0,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,8,",","""",H,u,i,m,i,l,p,a,n,"""",",",6,2,",",1,0,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,9,",","""",J,a,l,p,a,n, ,d,e, ,S,e,r,r,a,"""",",",3,5,",",7,4,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,0,",","""",L,a,n,d,a, ,d,e, ,M,a,t,a,m,o,r,o,s,"""",",",6,1,",",3,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,1,",","""",E,l, ,M,a,r,q,u,Ã,©,s,"""",",",2,0,7,",",2,0,2,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,2,",","""",P,e,d,r,o, ,E,s,c,o,b,e,d,o,"""",",",9,4,",",1,2,0,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,3,",","""",P,e,Ã,±,a,m,i,l,l,e,r,"""",",",3,0,",",4,4,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,4,",","""",Q,u,e,r,Ã,©,t,a,r,o,"""",",",1,2,7,5,",",1,1,4,6,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,5,",","""",S,a,n, ,J,o,a,q,u,Ã,­,n,"""",",",1,6,",",1,5,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,6,",","""",S,a,n, ,J,u,a,n, ,d,e,l, ,R,Ã,­,o,"""",",",4,2,6,",",3,5,5,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,7,",","""",T,e,q,u,i,s,q,u,i,a,p,a,n,"""",",",1,0,1,",",7,3,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,1,8,",","""",T,o,l,i,m,Ã,¡,n,"""",",",4,4,",",4,7,),;
I,N,S,E,R,T, ,I,N,T,O, ,E,s,t,u,d,i,a,n,t,e,s, ,V,A,L,U,E,S, ,(,9,9,9,",","""",N,o, ,e,s,p,e,c,i,f,i,c,a,d,o,"""",",",0,",",0,),;
